name: Compile LaTeX to PDF

on:
  push:
    branches:
      - master  # Adjust if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-english texlive-luatex texlive-science texlive-fonts-extra texlive-bibtex-extra texlive-pictures texlive-xetex texlive-plain-generic

      - name: Compile LaTeX files
        run: |
          mkdir -p public
          for file in *.latex; do
            lualatex -interaction=nonstopmode -output-directory=public "$file"
          done

      - name: List files before deployment
        run: ls -R public

      - name: Generate index.html
        run: |
          echo "<html><head>
            <title>Lecture Notes</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; padding: 20px; }
              h1 { color: #333; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 10px 0; }
              a { text-decoration: none; color: #007bff; font-size: 18px; }
              a:hover { text-decoration: underline; }
            </style>
          </head><body>
            <h1>Lecture Notes</h1>
            <ul>" > public/index.html


      - name: Upload PDFs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages  # <- This fixes the error
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
