name: Compile LaTeX to PDF

on:
  push:
    branches:
      - master  # Adjust if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-lang-english texlive-luatex texlive-science texlive-fonts-extra texlive-bibtex-extra texlive-pictures texlive-xetex texlive-plain-generic

      - name: Compile LaTeX files
        run: |
          mkdir -p public
          for file in *.latex; do
            lualatex -interaction=nonstopmode -output-directory=public "$file"
          done

      - name: Upload PDFs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
